// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: examples/cpp/PingPong/pingpong.proto
#ifndef GRPC_examples_2fcpp_2fPingPong_2fpingpong_2eproto__INCLUDED
#define GRPC_examples_2fcpp_2fPingPong_2fpingpong_2eproto__INCLUDED

#include "examples/cpp/PingPong/pingpong.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace pingpong {

// The service definition.
class PingPongService final {
 public:
  static constexpr char const* service_full_name() {
    return "pingpong.PingPongService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a ping
    virtual ::grpc::Status SendPing(::grpc::ClientContext* context, const ::pingpong::PingRequest& request, ::pingpong::PongResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pingpong::PongResponse>> AsyncSendPing(::grpc::ClientContext* context, const ::pingpong::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pingpong::PongResponse>>(AsyncSendPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pingpong::PongResponse>> PrepareAsyncSendPing(::grpc::ClientContext* context, const ::pingpong::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pingpong::PongResponse>>(PrepareAsyncSendPingRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Sends a ping
      virtual void SendPing(::grpc::ClientContext* context, const ::pingpong::PingRequest* request, ::pingpong::PongResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendPing(::grpc::ClientContext* context, const ::pingpong::PingRequest* request, ::pingpong::PongResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pingpong::PongResponse>* AsyncSendPingRaw(::grpc::ClientContext* context, const ::pingpong::PingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pingpong::PongResponse>* PrepareAsyncSendPingRaw(::grpc::ClientContext* context, const ::pingpong::PingRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendPing(::grpc::ClientContext* context, const ::pingpong::PingRequest& request, ::pingpong::PongResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pingpong::PongResponse>> AsyncSendPing(::grpc::ClientContext* context, const ::pingpong::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pingpong::PongResponse>>(AsyncSendPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pingpong::PongResponse>> PrepareAsyncSendPing(::grpc::ClientContext* context, const ::pingpong::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pingpong::PongResponse>>(PrepareAsyncSendPingRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendPing(::grpc::ClientContext* context, const ::pingpong::PingRequest* request, ::pingpong::PongResponse* response, std::function<void(::grpc::Status)>) override;
      void SendPing(::grpc::ClientContext* context, const ::pingpong::PingRequest* request, ::pingpong::PongResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::pingpong::PongResponse>* AsyncSendPingRaw(::grpc::ClientContext* context, const ::pingpong::PingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pingpong::PongResponse>* PrepareAsyncSendPingRaw(::grpc::ClientContext* context, const ::pingpong::PingRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendPing_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a ping
    virtual ::grpc::Status SendPing(::grpc::ServerContext* context, const ::pingpong::PingRequest* request, ::pingpong::PongResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendPing() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPing(::grpc::ServerContext* /*context*/, const ::pingpong::PingRequest* /*request*/, ::pingpong::PongResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendPing(::grpc::ServerContext* context, ::pingpong::PingRequest* request, ::grpc::ServerAsyncResponseWriter< ::pingpong::PongResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendPing<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendPing() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::pingpong::PingRequest, ::pingpong::PongResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::pingpong::PingRequest* request, ::pingpong::PongResponse* response) { return this->SendPing(context, request, response); }));}
    void SetMessageAllocatorFor_SendPing(
        ::grpc::MessageAllocator< ::pingpong::PingRequest, ::pingpong::PongResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::pingpong::PingRequest, ::pingpong::PongResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPing(::grpc::ServerContext* /*context*/, const ::pingpong::PingRequest* /*request*/, ::pingpong::PongResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendPing(
      ::grpc::CallbackServerContext* /*context*/, const ::pingpong::PingRequest* /*request*/, ::pingpong::PongResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendPing<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendPing() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPing(::grpc::ServerContext* /*context*/, const ::pingpong::PingRequest* /*request*/, ::pingpong::PongResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendPing() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPing(::grpc::ServerContext* /*context*/, const ::pingpong::PingRequest* /*request*/, ::pingpong::PongResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendPing(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendPing() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendPing(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPing(::grpc::ServerContext* /*context*/, const ::pingpong::PingRequest* /*request*/, ::pingpong::PongResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendPing(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendPing() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::pingpong::PingRequest, ::pingpong::PongResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::pingpong::PingRequest, ::pingpong::PongResponse>* streamer) {
                       return this->StreamedSendPing(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendPing(::grpc::ServerContext* /*context*/, const ::pingpong::PingRequest* /*request*/, ::pingpong::PongResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendPing(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pingpong::PingRequest,::pingpong::PongResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendPing<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendPing<Service > StreamedService;
};

}  // namespace pingpong


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_examples_2fcpp_2fPingPong_2fpingpong_2eproto__INCLUDED
